---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python2
    application: nginx
    NEW_ALIAS: nginx-load-balancer-1839090422.us-east-2.elb.amazonaws.com
  tasks:
    - name: create instances
      include_role: 
        name: create_instance
    - name: setup DNS
      include_role:
        name: route53
